### ISSUE TITLE
Convert Backend from TypeScript to JavaScript

### ISSUE THREAD

**Issue by SeanEstrella** [Tylermhh/404-day-visualizer-app#51]
### Description 

Using TSC to compile resulted in extra transcribed JavaScript files. This caused bloat and unnecessary issues. By converting the TypeScript files to JavaScript files permanently, ideally the issues will be resolved.

#### Tasks

- [x] Remove TypeScript Dependencies

- [x] Convert TypeScript Files to JavaScript

- [x] Update Build and Run Scripts

- [x] Refactor TypeScript Specific Code

- [x] Update Linting and Formatting Tools
